const mongoose = require("mongoose");
const Schema = mongoose.Schema;

const ItemSchema = new Schema({
  name: {
    type: String,
    required: true
  },
  date: {
    type: Date,
    default: Date.now
  }
});

// export as 'Item', the model generated by mongoose
module.exports = Item = mongoose.model("item", ItemSchema);
